### ISSUE TITLE
Great font resources

### ISSUE THREAD

**Issue by xuv** [opensourcedesign/fonts#7]
I'd like to suggest this great open source font resource by @raphaelbastide: http://usemodify.com/
And the CMS that supports it is open source too.

**Comment by flexbox** [comment]
Hello @xuv 
Feel free to edit the [README](https://github.com/opensourcedesign/fonts/blob/master/README.md) file with your link. 
When you have done it propose a pull-request :)

**Comment by jancborchardt** [comment]
This is now added to the resources page at https://opensourcedesign.net/resources/ :)

Via https://github.com/opensourcedesign/opensourcedesign.github.io/pull/241
