### ISSUE TITLE
OCRA and OCRB license clarification

### ISSUE THREAD

**Issue by raphaelbastide** [opensourcedesign/fonts#8]
Since the licenses of OCRA and B are blurry, unless a real clarification, I suggest not to include it in the repo.

**Comment by jancborchardt** [comment]
@raphaelbastide do you want to directly submit a pull request for removing them?

**Comment by raphaelbastide** [comment]
Maybe we can solve the issue first? Maybe Michael Demetriou author of the commit knows more about those licenses.

**Comment by jancborchardt** [comment]
cc @qwazix then. Do you know anything about that ^?

**Comment by qwazix** [comment]
They are indeed blurry, but after a careful read of them, without being a lawyer, I believe that the specific fonts I included are free software. The OCR-A official website explicitly mentions public domain (http://sourceforge.net/projects/ocr-a-font/) and 

> The version in this package descends from a set of Metafont
> definitions by Norbert Schwarz of Ruhr-Universitaet Bochum,
> bearing dates ranging from 1986 to 2010. He originally
> distributed it under a "non-commercial use only"
> restriction but has since released it for unrestricted use
> and distribution. See the README file for more details.

is a quote from the pdf that accompanies OCR-B, which I feel covers it. I cannot find the mentioned README file.

I also like to think that if it's good enough for debian packagers (https://packages.debian.org/wheezy/texlive-fonts-extra) it should cover us too.

**Comment by raphaelbastide** [comment]
Great, that’s a good thing to see that those great fonts are in the public domain.
I didn’t know about that :-)
Thank you @qwazix for this precision. I guess this issue can be closed.

**Comment by simonv3** [comment]
@raphaelbastide Thanks for being thorough about this!
